version: "2"
services:
  app:
    container_name: app
    build:
      dockerfile: ./containers/app/Dockerfile
      context: .
    restart: always
    ports:
      - "3005:3005"
    links:
      - mongo
  mongo:
    container_name: mongo
    build:
      dockerfile: ./containers/mongo/Dockerfile
      context: .
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: 'manabu'
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"